# Generated by Django 5.0.7 on 2024-08-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "number_of_months",
                    models.SmallIntegerField(verbose_name="Количество месяцев"),
                ),
            ],
            options={
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонементы",
                "ordering": ["-price"],
            },
        ),
        migrations.CreateModel(
            name="OrderAbonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(auto_now_add=True, verbose_name="Начало"),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Конец"),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Оплачен")),
                ("active", models.BooleanField(default=False, verbose_name="Активен")),
                (
                    "abonement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.abonement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Забронированный абонемент",
                "verbose_name_plural": "Забронированные абонементы",
            },
        ),
    ]
