# Generated by Django 5.0.7 on 2024-10-31 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workout", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Цена"
                    ),
                ),
                (
                    "number_of_months",
                    models.SmallIntegerField(verbose_name="Количество месяцев"),
                ),
            ],
            options={
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонементы",
            },
        ),
        migrations.CreateModel(
            name="OrderAbonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateField(blank=True, null=True, verbose_name="Начало"),
                ),
                ("end", models.DateField(blank=True, null=True, verbose_name="Конец")),
                ("status", models.BooleanField(default=False, verbose_name="Оплачен")),
                ("active", models.BooleanField(default=False, verbose_name="Активен")),
                (
                    "abonement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.abonement",
                        verbose_name="Абонемент",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Забронированный абонемент",
                "verbose_name_plural": "Забронированные абонементы",
            },
        ),
        migrations.CreateModel(
            name="OrderTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Конец"),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Оплачен")),
                ("active", models.BooleanField(default=False, verbose_name="Активен")),
                (
                    "rate",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trainings",
                        to="workout.rate",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trainings",
                        to="workout.trainer",
                        verbose_name="Тренер",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Забронированное занятие",
                "verbose_name_plural": "Забронированные занятия",
                "ordering": ["start"],
            },
        ),
    ]
