# Generated by Django 5.0.7 on 2024-08-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonement",
            name="price",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Цена"
            ),
        ),
    ]
