# Generated by Django 5.0.7 on 2024-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_abonement_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abonement",
            options={"verbose_name": "Абонемент", "verbose_name_plural": "Абонементы"},
        ),
    ]
