# Generated by Django 5.0.7 on 2024-08-05 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_abonement_options"),
        ("workout", "0004_reviews_rating_alter_reviews_trainer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="Дата начала")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Конец"),
                ),
                ("status", models.BooleanField(default=False, verbose_name="Оплачен")),
                ("active", models.BooleanField(default=False, verbose_name="Активен")),
                (
                    "rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trainings",
                        to="workout.rate",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trainings",
                        to="workout.trainer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Забронированное занятие",
                "verbose_name_plural": "Забронированные занятия",
            },
        ),
    ]
