# Generated by Django 5.0.7 on 2024-08-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0005_alter_orderabonement_start_alter_orderabonement_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderabonement",
            name="abonement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="orders.abonement",
                verbose_name="Абонемент",
            ),
        ),
    ]
