# Generated by Django 5.0.7 on 2024-08-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_orderabonement_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderabonement",
            name="phone",
        ),
    ]
