# Generated by Django 5.0.7 on 2024-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_remove_orderabonement_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderabonement",
            name="end",
            field=models.DateField(blank=True, null=True, verbose_name="Конец"),
        ),
        migrations.AlterField(
            model_name="orderabonement",
            name="start",
            field=models.DateField(blank=True, null=True, verbose_name="Начало"),
        ),
    ]
