# Generated by Django 5.0.7 on 2024-08-03 12:25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import workout.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название тарифа"),
                ),
                (
                    "count_minutes",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Количество минут"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000,
                        max_digits=10,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание тарифа"),
                ),
            ],
            options={
                "verbose_name": "Тариф тренера",
                "verbose_name_plural": "Тарифы тренеров",
                "ordering": ["-price"],
            },
        ),
        migrations.CreateModel(
            name="RatingStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SmallIntegerField(default=0, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("fitness", "Инструктор тренажерного зала"),
                            ("pool", "Инструктор бассейна"),
                            ("yoga", "Инструктор йоги"),
                        ],
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="trainers/trainer.jpg",
                        upload_to=workout.service.get_path_for_avatar_for_trainer,
                        verbose_name="Аватар",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
                (
                    "rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workout.rate",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="workout.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о тренерах",
                "verbose_name_plural": "Отзывы о тренерах",
            },
        ),
        migrations.CreateModel(
            name="RatingTrainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "star",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workout.ratingstar",
                        verbose_name="звезда",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="workout.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг тренера",
                "verbose_name_plural": "Рейтинг тренеров",
            },
        ),
    ]
