# Generated by Django 5.0.7 on 2024-10-31 14:27

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
import workout.service
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Заголовок статьи"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ("pk",),
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название тарифа"),
                ),
                (
                    "count_minutes",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Количество минут"
                    ),
                ),
                ("price", models.SmallIntegerField(default=1000, verbose_name="Цена")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание тарифа"),
                ),
            ],
            options={
                "verbose_name": "Тариф тренера",
                "verbose_name_plural": "Тарифы тренеров",
                "ordering": ["-price"],
            },
        ),
        migrations.CreateModel(
            name="RatingStar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SmallIntegerField(default=0, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Звезда рейтинга",
                "verbose_name_plural": "Звезды рейтинга",
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на рассылку",
                "verbose_name_plural": "Подписки на рассылку",
            },
        ),
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("fitness", "Инструктор тренажерного зала"),
                            ("pool", "Инструктор бассейна"),
                            ("yoga", "Инструктор йоги"),
                        ],
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="trainers/trainer.jpg",
                        upload_to=workout.service.get_path_for_avatar_for_trainer,
                        verbose_name="Аватар",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Биография")),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        max_length=5000, null=True, verbose_name="Текст отзыва"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Создано"
                    ),
                ),
                (
                    "rating",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workout.ratingstar",
                        verbose_name="рейтинг",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_reviews",
                        to="workout.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о тренерах",
                "verbose_name_plural": "Отзывы о тренерах",
                "ordering": ["-created_at"],
            },
        ),
    ]
