# Generated by Django 5.0.7 on 2025-01-26 20:51

import django.db.models.deletion
import workout.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=workout.service.get_path_for_all_images_by_trainer,
                        verbose_name="Фото",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="workout.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото тренера",
                "verbose_name_plural": "Фото тренеров",
            },
        ),
    ]
