# Generated by Django 5.0.7 on 2024-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainer",
            name="rate",
        ),
    ]
