# Generated by Django 5.0.7 on 2024-08-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0005_reviews_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка на рассылку",
                "verbose_name_plural": "Подписки на рассылку",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ("pk",),
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
