# Generated by Django 5.0.7 on 2024-08-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0007_alter_subscription_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Отзыв о тренерах",
                "verbose_name_plural": "Отзывы о тренерах",
            },
        ),
    ]
