# Generated by Django 5.0.7 on 2024-08-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0008_alter_reviews_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="price",
            field=models.SmallIntegerField(default=1000, verbose_name="Цена"),
        ),
    ]
